### PR TITLE
fix: Support nested nx repositories

### LINKED ISSUE #46: Affected files not working correctly when monorepo is nested in repository
Hey!

Firstly, Awesome plugin :)

I found that the affected files (and therefore release generation) does not work correctly when the nx monorepo is nested inside the git repository. For example:
```
backend/
frontend/
    packages/
        one/
            file.js
            package.json
        two/
            package.json
    package.json
```

The [affected files calls here](https://github.com/TheUnderScorer/nx-semantic-release/blob/master/packages/nx-semantic-release/src/common/git.ts#L33-L35), will not return any files being touched in `one` or `two`, because the root of the paths in `affectedFiles` are the git root, not the nx root. 

In the above structure, if the last commit touches `file.js`, affected files will be:
`affectedFiles: [ 'frontend/packages/one/file.js' ]`
And the `filteredGraph` will be empty.

I hacked in some code in the node_modules and confirmed that the generation is fine after removing the `frontend/` path prefix.

You can see it in my test project here: https://github.com/Weetbix/nx-monorepo-example/commit/83955e47b55af5afa0e4b29ee2b43f0e3466a95d

### PR DESCRIPTION
**Pull request by Weetbix**
This fixes #46 

We can tell if the nx monorepo is nested because there will be a difference between the git root and the nx root. So we trim all filepaths that start with that difference.

Additionally I don't include any files outside of the nx folder.

I've tested it on:
- My nested monorepo and it works
- Non-nested mono repo and it works as before

### CODE REVIEW

File: packages/nx-semantic-release/src/common/git.ts [hunk 1]
```diff
@@ -82,12 +83,28 @@ export function shouldSkipCommit(
...
+    .filter(Boolean)
+    .filter((filePath: string) => {
+      // only include files inside the nx root
+      return filePath.match(nxPathPart);
+    })
+    .map((filePath: string) => {
+        // The filepaths start from the root of the git repository, but
+        // in our case we want them to start from the nx root.
+        return filePath.replace(nxPathPart, '');
+    });
```
Comment (TheUnderScorer) [inline packages/nx-semantic-release/src/common/git.ts:109]: I would suggest one small change:

```typescript
return files
    .toString()
    .split('\n')
    .map((line) => line?.split('\t')?.[1])
    .filter(Boolean)
    .filter((filePath: string) => {
      // only include files inside the nx root
      return filePath.match(nxPathPart);
    })
    .map((filePath: string) => {
        // The filepaths start from the root of the git repository, but
        // in our case we want them to start from the nx root.
        return filePath.replace(nxPathPart, '');
    });
```

With that we can avoid calling `.filter(Boolean)` twice 😄

**Review by TheUnderScorer — CHANGES_REQUESTED** [review]

**Comment by TheUnderScorer** [comment]
Thanks for the PR @Weetbix!

I left one small comment, but other than that looks good!

File: packages/nx-semantic-release/src/common/git.ts (hunk 1 above)
Comment (Weetbix) [reply packages/nx-semantic-release/src/common/git.ts]: Ah yeah good one :)

Updated and tested, still working 👍

**Comment by TheUnderScorer** [comment]
Thanks, merged!
